// Copyright 2010 two forty four a.m. LLC <http://www.twofortyfouram.com>
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at <http://www.apache.org/licenses/LICENSE-2.0>
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package org.acm.steidinger.calendar.localePlugin;

/**
 * Utility class containing constants for the <i>Locale</i> Developer Platform
 */
/*
 * This class is NOT part of the public API
 */
public final class Constants
{

	/**
	 * Log tag for logcat messages generated by the <i>Locale</i> Developer Platform
	 */
	/*
	 * This is NOT a public field. Third party apps should NOT use this log tag for their own log messages
	 */
	public static final String LOG_TAG = "CalendarCondition"; //$NON-NLS-1$

    /**
     * Type: {@code boolean}
     * <p>
     * SharedPreference key for retrieving a boolean as to whether the license has been agreed to
     */
    static final String PREFERENCE_BOOLEAN_IS_LICENSE_AGREED = "IS_LICENSE_AGREED"; //$NON-NLS-1$

    /**
     * TYPE: {@code boolean}
     * <p>
     * True means calendar must contain an appointment.
     */
    static final String BUNDLE_EXTRA_CALENDAR_STATE = "org.acm.steidinger.calendar.localePlugin.extra.STATE"; //$NON-NLS-1$

    static final String BUNDLE_EXTRA_CALENDAR_ID = "org.acm.steidinger.calendar.localePlugin.extra.ID";

    /**
     * Enables logging within the app. Typically, this should be disabled before creating a release version of the app. Logging
     * has *significant* performance implications.
     */
    static final boolean IS_LOGGABLE = true;

    public static final String BUNDLE_EXTRA_LEAD_TIME = "org.acm.steidinger.calendar.localePlugin.extra.LEAD_TIME";
    public static final String BUNDLE_EXTRA_EXCLUSION = "org.acm.steidinger.calendar.localePlugin.extra.EXCLUSION";
}
