/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.twofortyfouram.locale.platform;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int twofortyfouram_locale_dialog_primary_message=0x7f050000;
        public static final int twofortyfouram_locale_dialog_secondary_message=0x7f050001;
        public static final int twofortyfouram_locale_menu_dontsave=0x7f050003;
        public static final int twofortyfouram_locale_menu_help=0x7f050002;
        public static final int twofortyfouram_locale_menu_save=0x7f050004;
    }
    public static final class layout {
        public static final int twofortyfouram_locale_dialog=0x7f020000;
    }
    public static final class menu {
        public static final int twofortyfouram_locale_help_save_dontsave=0x7f040000;
    }
    public static final class string {
        /**  A toast message that appears if an application that is being launched isn't available.  There is no character length maximum, although this message will only appear on the screen for about 5 seconds in a Toast message so it should be short enough to be comprehended before it disappears 
         */
        public static final int twofortyfouram_locale_application_not_available=0x7f030000;
        /**  A format string for breadcrumbs.  For left to right languages, such as English, the format will look something like "Main Activity > Sub Activity > Sub Activity 2".  Item #1 is the previous path, item #2 is the separator, and item #3 is the current item   
         */
        public static final int twofortyfouram_locale_breadcrumb_format=0x7f030001;
        /**  The separator character for breadcrumbs 
         */
        public static final int twofortyfouram_locale_breadcrumb_separator=0x7f030002;
        /**  The button that performs a search for the app on the Market or on <www.twofortyfouram.com>.  MDPI 17 character maximum 
         */
        public static final int twofortyfouram_locale_marketactivity_dialog_button_install=0x7f030004;
        /**  The primary message of the MarketActivity dialog.  There is no character length maximum 
         */
        public static final int twofortyfouram_locale_marketactivity_dialog_primary_message=0x7f030005;
        /**  The secondary message of the MarketActivity dialog.  The word "Install" should match the twofortyfouram_locale_marketactivity_dialog_button_install string.  There is no character length maximum 
         */
        public static final int twofortyfouram_locale_marketactivity_dialog_secondary_message=0x7f030006;
        /**  The title of the MarketActivity.  MDPI 21 character maximum 
         */
        public static final int twofortyfouram_locale_marketactivity_dialog_title=0x7f030003;
    }
}
